version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: mongodbtest
    volumes:
      - mongodb_data:/data/db

  api:
    build: .
    container_name: local-connect-api
    restart: always
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      MONGO_URL: ${MONGO_URL}
    depends_on:
      - mongodb

volumes:
  mongodb_data:
